name: Pull request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  "build_test":
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Create dummy aws-exports.js
        run: echo "export default {}"> src/aws-exports.js
      - name: Build
        run: npm run build
      - name: Check code style
        run: npm run lint
      - name: Test
        run: npm test
